#!/bin/bash
# Automatically added by dh_installinit

NAME=jolokia-munin-plugin
[ -r /etc/default/$NAME ] && . /etc/default/$NAME

if [ -x "/etc/init.d/$NAME" ] && [ "$AS_DAEMON"=="true" ]; then
	update-rc.d $NAME defaults >/dev/null
	invoke-rc.d $NAME start || exit $?
fi
# End automatically added section
