#!/bin/bash
# Automatically added by dh_installinit
if [ -x "/etc/init.d/jolokia-munin-plugin" ]; then
	update-rc.d jolokia-munin-plugin defaults >/dev/null
	invoke-rc.d jolokia-munin-plugin start || exit $?
fi
# End automatically added section
