#!/bin/bash

NAME=jolokia-munin-plugin
[ -r /etc/default/$NAME ] && . /etc/default/$NAME

if [ "$1" = "autoconf" ]; then
	echo yes
    exit 0
fi
if [ "$AS_DAEMON"=="true" ]; then
	command="fetch"
	if [ "$1" != "" ]; then
		command="$1"
	fi
#	(echo $command;  echo "quit";) | netcat $BIND_TO $PORT

fi

$JAVA $JAVA_ARGS -jar $JM_JAR $1
